[preprocessing]
source_url = http://10.0.1.8/TRAIN_SET.zip
raw_dir = data/raw
clean_dir = data/clean
exp_dir = data/clean/exp
classes_raw_dirs = {"Diabetes": 1, "PGOV_Glaukom": 2, "SklerózaMultiplex": 3, "SucheOko": 4, "ZdraviLudia": 5}